[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.stdout.log
stderr_logfile=/var/log/nginx.stderr.log

[program:node-backend]
directory=/app
command=npm run server
autostart=true
autorestart=true
environment=NODE_ENV="production",INTERNAL_PORT="5000"
stdout_logfile=/var/log/node-backend.log
stderr_logfile=/var/log/node-backend.err.log

[program:python-backend]
directory=/app/bankstatement
command=gunicorn --bind 0.0.0.0:5001 --workers 2 --timeout 120 app:app
autostart=true
autorestart=true
stdout_logfile=/var/log/python-backend.log
stderr_logfile=/var/log/python-backend.err.log
